import { auth } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { redirect } from "next/navigation";
import { RoadmapClient } from "./roadmap-client";

export default async function RoadmapPage() {
  const session = await auth();
  if (!session?.user?.id) redirect("/login");

  const profile = await prisma.studentProfile.findUnique({
    where: { userId: session.user.id },
    include: {
      roadmaps: {
        orderBy: { createdAt: 'desc' }
      }
    }
  });

  if (!profile) {
    redirect("/dashboard/profile");
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">AI Career Roadmap</h1>
        <p className="text-zinc-400 mt-2">
          Discover your skill gaps and get a personalized learning plan generated by IBM Watsonx.
        </p>
      </div>

      <RoadmapClient 
        hasResume={!!profile.resumeUrl} 
        roadmaps={profile.roadmaps} 
      />
    </div>
  );
}
